datasets:
- name: arctic32m
  path: data/arctic32m-vrt/
  filename_epsg: 4326
  filename_tile_size: 1
- name: ned10m
  path: data/ned10m/
  filename_epsg: 4326
  filename_tile_size: 1
  filename_pattern: '{lat}{lon}.tif'
- name: srtm30m
  path: data/srtm30m/
  filename_epsg: 4326
  filename_tile_size: 1
- name: aw3d30
  path: data/aw3d30/
  filename_epsg: 4326
  filename_tile_size: 1
  filename_pattern: '{lat}{lon}.tif'
max_locations_per_request: 500
access_control_allow_origin: '*'
